# Numpy

## Introdução

A primeira coisa que precisamos fazer para usar o ``NumPy`` em um código, é importar a biblioteca.

````import numpy as np````

Com esse alias, o nosso código fica bem menor, facilitando para outras pessoas entenderem ele depois. Como o alias é comum na comunidade, ele também não gera confusões, e permite sabermos sempre quando alguma operação feita é nativa do ``NumPy``.

In [2]:
import numpy as np

O método mais comum de criar um _ndarray_ é usando a função ``np.array``.

In [4]:
vetor = np.array([1, 2, 3])
print(vetor)
print(type(vetor))

[1 2 3]
<class 'numpy.ndarray'>


Podemos criar também uma tabela com duas dimensões. Nesse caso, temos uma matriz.

In [5]:
matriz = np.array([[1, 2], [3, 4]])
print(matriz)

[[1 2]
 [3 4]]


obs: Matematicamente, quando temos 3 dimensões ou mais, nós chamamos esse objeto de um **tensor**.

Criação de um array de zeros

In [26]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Criação de um array de uns

In [27]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

criação de um array de valores quaisquer

In [28]:
np.ones((2, 2)) * 10

array([[10., 10.],
       [10., 10.]])

In [29]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

Também temos o ``full_like``, que copia o formato de uma matriz que já tenha sido declarada antes

In [30]:
np_mat = np.array([[1, 2,  3,  4,  5,  6,  7], 
                   [8, 9, 10, 11, 12, 13, 14]])

In [31]:
np.full_like(np_mat, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

Outra função para criação de arrays é ``np.repeat``. Ela repete um determinado array na direção do eixo escolhido.

Para um vetor de 1D, temos apenas 1 eixo, mas para matrizes, tempos dois. O eixo 0 é linha, o eixo 1 é coluna.

In [32]:
arr = np.array([1, 2, 3])

In [33]:
r1 = np.repeat(arr, 3)

In [34]:
print(r1)

[1 1 1 2 2 2 3 3 3]


Números pseudo-aleatórios

In [35]:
np.random.random_sample((4, 2))

array([[0.23570188, 0.77184563],
       [0.80430399, 0.51096906],
       [0.44532283, 0.03368835],
       [0.59133819, 0.06922289]])

In [36]:
np.random.rand(4, 2)

array([[0.16055176, 0.86680612],
       [0.00147073, 0.42872156],
       [0.89987927, 0.55293864],
       [0.37471609, 0.46936278]])

In [37]:
np.random.randint(7, size=(3, 3))

array([[1, 2, 6],
       [6, 6, 5],
       [3, 1, 3]])

In [38]:
np.random.randint(5, high=10, size=10)

array([8, 6, 6, 7, 8, 8, 5, 5, 5, 6])

## Matemática com NumPy

In [39]:
vec1 = np.array([2., 4., 6., 8.])
vec2 = np.array([1., 2., 3., 4.])

print('Soma', vec1 + vec2)            # Soma
print('Subtração', vec1 - vec2)       # subtração
print('Multiplicação', vec1 * vec2)   # Multiplicação
print('Divisão', vec1 / vec2)         # Divisão
print('Exponenciação', vec1 ** vec2)  # exponenciação  


Soma [ 3.  6.  9. 12.]
Subtração [1. 2. 3. 4.]
Multiplicação [ 2.  8. 18. 32.]
Divisão [2. 2. 2. 2.]
Exponenciação [2.000e+00 1.600e+01 2.160e+02 4.096e+03]


 operações com escalares

In [42]:
vec2 += 2

In [44]:
print('Soma', vec2 + 2)             # Somar
print('Subtração', vec2 - 2)        # Subtrair
print('Multiplicação', vec2 * 2)    # Multiplicar
print('Divisão', vec2 / 2)          # Dividir
print('Potenciação',vec2 ** 2)      # Potência (elevar a um número)

Soma [5. 6. 7. 8.]
Subtração [1. 2. 3. 4.]
Multiplicação [ 6.  8. 10. 12.]
Divisão [1.5 2.  2.5 3. ]
Potenciação [ 9. 16. 25. 36.]


## Álgebra Linear e Estatística básica

### Álgebra Linear

Produto Escalar

In [15]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([2, 2, 3])
vec1.dot(vec2)

15

In [16]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([2, 2, 3])
vec1 @ vec2

15

Produto Vetorial

In [17]:
matrix1 = np.array([[1, 1, 1],
                    [1, 2, 3],
                    [1, 1, 1]])
matrix2 = np.array([[1, 1, 1],
                    [1, 1, 1],
                    [1, 1, 1]])

In [18]:
matrix1.dot(matrix2)

array([[3, 3, 3],
       [6, 6, 6],
       [3, 3, 3]])

In [19]:
matrix1 @ matrix2

array([[3, 3, 3],
       [6, 6, 6],
       [3, 3, 3]])

Matriz identidade

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Matriz Transposta

In [22]:
np.transpose(matrix1)

array([[1, 1, 1],
       [1, 2, 1],
       [1, 3, 1]])

In [23]:
matrix1.T

array([[1, 1, 1],
       [1, 2, 1],
       [1, 3, 1]])

Determinante

In [25]:
np.linalg.det(matrix2)

0.0

### Estatística

In [6]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.min(stats)

1

In [8]:
np.max(stats)

6

In [9]:
np.min(stats, axis=1) # Pega o menor valor de cada linha 

array([1, 4])

In [10]:
np.max(stats, axis=0) # Pega o maior valor de cada coluna

array([4, 5, 6])

In [11]:
np.sum(stats, axis=0) # Faz a soma dos valores de cada coluna

array([5, 7, 9])

In [12]:
np.mean(stats) # Valor médio de todos os elementos do array

3.5

In [13]:
np.mean(stats, axis=0) # Valor médio de cada coluna do array

array([2.5, 3.5, 4.5])

In [14]:
np.mean(stats, axis=1) # Valor médio de cada linha do array

array([2., 5.])

# Pandas

Importando o pacote

In [48]:
import pandas as pd

## Introdução

DataFrame

In [52]:
dados = [['Fulano',   1.69, 87.0],
         ['Sicrana',  1.59, 56.5],
         ['Beltrana', 1.69, 90.3],
         ['João',     1.74, 78.6]] 

In [53]:
df = pd.DataFrame(dados, columns=['Nome', 'altura', 'peso'])

In [54]:
df

Nome  altura  peso
0    Fulano    1.69  87.0
1   Sicrana    1.59  56.5
2  Beltrana    1.69  90.3
3      João    1.74  78.6

In [55]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


Series

In [56]:
minha_lista = [87.0, 56.5, 90.3, 78.6]

In [57]:
serie = pd.Series(minha_lista, index=['Fulano', 'Sicrana', 'Beltrana', 'João'])

In [58]:
serie

Fulano      87.0
Sicrana     56.5
Beltrana    90.3
João        78.6
dtype: float64

### Pandas Series

In [59]:
minha_lista = [10, 20, 30, 40]
serie = pd.Series(minha_lista)

serie.index = ['a', 'b', 'c', 'd']

serie.astype(np.float32) 

a    10.0
b    20.0
c    30.0
d    40.0
dtype: float32

### Pandas DataFrame

## Tratamento e Limpeza de Dadoa 

### Exploração de Dados